import { useEventListener } from '@vueuse/core'
import { computed, onScopeDispose, shallowRef } from 'vue'
import {
  clampFloatingPosition,
  dockFloatingPosition,
  FLOATING_BUTTON_SIZE,
  getFloatingPanelStyle,
  getNearestFloatingEdge,
} from '../utils/floatingPosition'
import type { ShallowRef } from 'vue'
import type { FloatingEdge, FloatingPosition } from '../utils/floatingPosition'

/**
 * Controls pointer dragging, edge docking, and panel placement for the launcher.
 * Pointer capture keeps mouse, pen, and touch drags attached to the button.
 *
 * @param button - Mounted launcher button used for pointer capture.
 * @returns Position styles and event handlers for the launcher.
 */
export function useFloatingLauncher(
  button: Readonly<ShallowRef<HTMLButtonElement | null>>,
) {
  const viewport = shallowRef({
    width: window.innerWidth,
    height: window.innerHeight,
  })
  const edge = shallowRef<FloatingEdge>('right')
  const position = shallowRef(
    dockFloatingPosition(
      {
        x: viewport.value.width,
        y: viewport.value.height - FLOATING_BUTTON_SIZE - 20,
      },
      viewport.value,
      edge.value,
    ),
  )
  const isDragging = shallowRef(false)
  let gesture:
    | { pointerId: number; start: FloatingPosition; origin: FloatingPosition }
    | undefined
  let suppressClick = false

  const buttonStyle = computed(() => ({
    left: `${position.value.x}px`,
    top: `${position.value.y}px`,
    width: `${FLOATING_BUTTON_SIZE}px`,
    height: `${FLOATING_BUTTON_SIZE}px`,
  }))
  const panelStyle = computed(() =>
    getFloatingPanelStyle(position.value, viewport.value),
  )

  /**
   * Starts a primary-pointer gesture without treating a simple click as a drag.
   *
   * @param event - Pointer press on the launcher.
   */
  function onPointerDown(event: PointerEvent) {
    if (!event.isPrimary || event.button !== 0 || gesture || !button.value) {
      return
    }
    const rect = button.value.getBoundingClientRect()
    gesture = {
      pointerId: event.pointerId,
      start: { x: event.clientX, y: event.clientY },
      origin: { x: rect.left, y: rect.top },
    }
    suppressClick = false
    button.value.setPointerCapture(event.pointerId)
  }

  /**
   * Moves the button once the pointer travels beyond the click tolerance.
   *
   * @param event - Movement from the captured pointer.
   */
  function onPointerMove(event: PointerEvent) {
    if (!gesture || event.pointerId !== gesture.pointerId) {
      return
    }
    const x = event.clientX - gesture.start.x
    const y = event.clientY - gesture.start.y
    if (!isDragging.value && Math.hypot(x, y) < 6) {
      return
    }
    event.preventDefault()
    isDragging.value = true
    suppressClick = true
    position.value = clampFloatingPosition(
      {
        x: gesture.origin.x + x,
        y: gesture.origin.y + y,
      },
      viewport.value,
    )
  }

  /**
   * Ends or cancels a gesture and releases capture before docking the button.
   */
  function finishGesture() {
    const pointerId = gesture?.pointerId
    gesture = undefined
    if (pointerId !== undefined && button.value?.hasPointerCapture(pointerId)) {
      button.value.releasePointerCapture(pointerId)
    }
    if (isDragging.value) {
      edge.value = getNearestFloatingEdge(position.value, viewport.value)
      position.value = dockFloatingPosition(
        position.value,
        viewport.value,
        edge.value,
      )
    }
    isDragging.value = false
  }

  /**
   * Uses the release coordinates before snapping to the nearest viewport edge.
   *
   * @param event - Release from the active pointer.
   */
  function onPointerUp(event: PointerEvent) {
    if (event.pointerId !== gesture?.pointerId) {
      return
    }
    onPointerMove(event)
    finishGesture()
  }

  /**
   * Recovers from interrupted touch gestures or lost pointer capture.
   *
   * @param event - Cancellation from the active pointer.
   */
  function onPointerCancel(event: PointerEvent) {
    if (event.pointerId === gesture?.pointerId) {
      suppressClick = true
      finishGesture()
    }
  }

  /**
   * Rejects the click generated by a drag while preserving keyboard activation.
   *
   * @param event - Pointer or keyboard click on the launcher.
   * @returns Whether the click should toggle the download panel.
   */
  function shouldToggle(event: MouseEvent) {
    return event.detail === 0 || !suppressClick
  }

  useEventListener(window, 'blur', finishGesture)
  useEventListener(window, 'resize', () => {
    finishGesture()
    viewport.value = { width: window.innerWidth, height: window.innerHeight }
    position.value = dockFloatingPosition(
      position.value,
      viewport.value,
      edge.value,
    )
  })
  onScopeDispose(finishGesture)

  return {
    isDragging,
    buttonStyle,
    panelStyle,
    onPointerDown,
    onPointerMove,
    onPointerUp,
    onPointerCancel,
    shouldToggle,
  }
}
